version: "3"

tasks:
  install:
    desc: Install Python dependencies
    cmds:
      - uv pip install django-boostrap5

  fixtures:
    desc: Run migrations and load sample data
    cmds:
      - uv run manage.py migrate
      - uv run manage.py makemigrations catalog
      - uv run manage.py migrate catalog
      - uv run manage.py loaddata catalog

  run:
    desc: Start the development server
    cmds:
      - uv run manage.py runserver
