version: '3'

tasks:

  docs:
    cmds:
      - mkdocs serve -a localhost:8001
    silent: true

  cleanup:
    cmds:
      - find . -type d -name "__pycache__" -exec rm -r {} +
      - rm -rf .nox dist
    silent: true
