# Generated by Django 6.0.2 on 2026-02-09 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, help_text="Author's date of birth", null=True)),
                ('biography', models.TextField(blank=True, help_text='Short biography')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured on the homepage')),
                ('website', models.URLField(blank=True, help_text="Author's personal website")),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official publisher name', max_length=200)),
                ('website', models.URLField(blank=True, help_text='Publisher website URL')),
                ('founded_year', models.IntegerField(help_text='Year the publisher was founded')),
                ('is_active', models.BooleanField(default=True, help_text='Currently accepting submissions')),
                ('description', models.TextField(blank=True, help_text='About this publisher')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Full book title', max_length=300)),
                ('summary', models.TextField(blank=True, help_text='Brief plot summary')),
                ('price', models.DecimalField(decimal_places=2, help_text='Retail price in USD', max_digits=6)),
                ('rating', models.FloatField(default=0.0, help_text='Average reader rating (0-5)')),
                ('pages', models.IntegerField(default=0, help_text='Number of pages')),
                ('is_available', models.BooleanField(default=True, help_text='Currently in stock')),
                ('publication_date', models.DateField(blank=True, help_text='First publication date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='books', to='catalog.author')),
                ('genres', models.ManyToManyField(related_name='books', to='catalog.genre')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='catalog.publisher')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PublisherAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='catalog.publisher')),
            ],
            options={
                'verbose_name': 'publisher address',
                'verbose_name_plural': 'publisher addresses',
            },
        ),
    ]
